# Generated by Django 3.0.2 on 2021-01-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tag', models.TextField()),
                ('make', models.CharField(max_length=30)),
                ('img', models.FilePathField(path='/img')),
            ],
        ),
    ]
